mongodb:
  image: mongo
  ports:
    - "27017:27017"

app:
  image: mhart/alpine-node
  volumes:
    - ./app:/app
  links:
    - mongodb
  ports:
    - "3000:3000"
  working_dir: /app
  entrypoint: node geoscam.js
